[project]
name = "pyUserSession"
version = "0.0.1"
readme = "README.md"
license = {file = "LICENSE"}

dependencies = [
    'fastapi>=0.104.1,<0.105',
    'pyjwt[crypto]>=2.8.0,<2.9',
    'requests>=2.31.0,<2.32',
    'uvicorn[all]>=0.23.2,<0.24'
]

[project.optional-dependencies]
dev = [
    'black==23.10.1',
    'ruff==0.1.6',
    'isort==5.12.0',
]

[tool.isort]
profile = "black"