[project]
name = "backend_api"
version = "0.0.1"
readme = "README.md"
license = {file = "LICENSE"}

dependencies = [
    'fastapi>=0.104.1,<0.105',
    'pyjwt[crypto]>=2.8.0,<3',
    'requests>=2.31.0,<3',
    'uvicorn[all]>=0.23.2,<0.24',
    'azure-identity>=1.15.0,<2',
    'azure-keyvault-secrets>=4.7.0,<5',
    'pydantic-settings>=2.1.0,<3',
    'httpx>=0.25.2,<0.26',
    'asyncpg>=0.29.0,<1',
    'sqlmodel>=0.0.14,<0.1.0',
    'pydantic>=2.5.2,<3',# sqlmodel dependes on pydantic <2.0.0!
    'alembic>=1.13.0,<2',
]

[project.optional-dependencies]
dev = [
    'black==23.10.1',
    'ruff==0.1.6',
    'isort==5.12.0',
    'pytest==7.4.3',
]

[tool.isort]
profile = "black"