# In final implementation, move this file one diectory level higher and reference all services here
version: "3.9"


services:
    backend_api:
        build:
            context: 
                ./backendAPI
            target: dev
        image: backend_api:test
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - postgres-user=$postgres-user
            - postgres-password=$postgres-password
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_PORT=$MONGODB_PORT

    postgres:
        container_name: postgres-test
        volumes:
            - test-postgres-data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - postgres-user=$postgres-user
            - postgres-password=$postgres-password
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_PORT=$MONGODB_PORT

volumes:
    test-postgres-data: