version: "3.9"

services:
    backend_api:
        container_name: "backendAPI"
        build:
            context: ./backendAPI
            target: prod
        # TBD: consider moving into compose.override.yml - in case a build stage is involved
        volumes:
            - ./src:/app
        ports:
            - "8660:8660"

    postgres:
        image: postgres:13-alpine
