# version: "3.9"

services:
    backend_api:
        build:
            context: ./backendAPI
            target: prod
        volumes:
            - ./backendAPI:/app
        # ports:
        #     - "80:80"

    postgres:
        container_name: "postgres"
        image: postgres:16.1-alpine

    frontend_svelte:
        build:
            context: ./frontend_svelte

    redis:
        container_name: "redis"
        image: redis/redis-stack-server:7.2.0-v6
        #redis:7.2-alpine