version: "3.9"

services:
    backendAPI:
        build:
            target: dev
        env_file:
            - ./backendAPI/src/.env

    postgres:
        volumes:
            - dev-postgres-data:/var/lib/postgresql/data/
        env_file:
        # TBD: change to ./backend/src/.env, when compose file is moved one level up
            - ./backendAPI/src/.env

volumes:
    dev-postgres-data: