# In final implementation, move this file one diectory level higher and reference all services here
version: "3.9"


services:
    backend_api:
        build:
            # context: 
            #     ./backendAPI
            target: dev
        image: backend_api:test
        depends_on:
            - postgres
        environment:
            - KEYVAULT_HEALTH=$KEYVAULT_HEALTH
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_PORT=$MONGODB_PORT
        networks:
            - test_network
        ports:
            - "8660:8660"
        volumes:
            - test-app-data:/data

    postgres:
        container_name: $POSTGRES_HOST
        volumes:
            - test-postgres-data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_HOST=$POSTGRES_HOST
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            # - REDIS_HOST=$REDIS_HOST
            # - REDIS_PORT=$REDIS_PORT
            # - MONGODB_HOST=$MONGODB_HOST
            # - MONGODB_PORT=$MONGODB_PORT
        networks:
            - test_network

volumes:
    test-postgres-data:
    test-app-data:

networks:
    test_network:
        name: test_network