version: "3.9"

services:
    backend_api:
        build:
            target: dev
        env_file:
            - ./backendAPI/src/.env

    postgres:
        volumes:
            - dev-postgres-data:/var/lib/postgresql/data/
        env_file:
        # TBD: change to ./backend/src/.env, when compose file is moved one level up
            - ./backendAPI/src/.env
        # command: ["postgres", "-c", "listen_addresses=*", "-c", "POSTGRES_DB=${DEV_POSTGRES_DB}", "-c", "POSTGRES_USER=${DEV_POSTGRES_USER}", "-c", "POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}"]

volumes:
    dev-postgres-data: