version: "3.9"

services:
    backend_api:
        build:
            # context: 
            #     ./backendAPI
            target: dev
        # image: backend_api:test
        depends_on:
            - postgres
        environment:
            - KEYVAULT_HEALTH=$KEYVAULT_HEALTH
            - POSTGRES_HOST=$POSTGRES_HOST
            # - POSTGRES_PORT=$POSTGRES_PORT
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - REDIS_SESSION_DB=$REDIS_SESSION_DB
            - REDIS_PASSWORD=$REDIS_PASSWORD
            - MONGODB_HOST=$MONGODB_HOST
            - MONGODB_PORT=$MONGODB_PORT
        networks:
            - test_network
        ports: 
            - "8670:80"
        volumes:
            - test-app-data:/data

    postgres:
        container_name: test_postgres
        volumes:
            - test-postgres-data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_HOST=$POSTGRES_HOST
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            # - REDIS_HOST=$REDIS_HOST
            # - REDIS_PORT=$REDIS_PORT
            # - MONGODB_HOST=$MONGODB_HOST
            # - MONGODB_PORT=$MONGODB_PORT
        networks:
            - test_network

    frontend_svelte:
        build:
            target: build
            args:
                - REDIS_HOST=$REDIS_HOST
                - REDIS_PORT=$REDIS_PORT
                - REDIS_SESSION_DB=$REDIS_SESSION_DB
                - REDIS_PASSWORD=$REDIS_PASSWORD
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - REDIS_SESSION_DB=$REDIS_SESSION_DB
            - REDIS_PASSWORD=$REDIS_PASSWORD
        networks:
            - test_network
        command: 
            sh -c "npm install && npm run dev"
            # npm run dev

    redis:
        container_name: test_redis
        image: redis/redis-stack:7.2.0-v6
        environment:
            - REDIS_ARGS=$REDIS_ARGS
        volumes:
            - test-redis-data:/data
        # environment:
            # - REDIS_HOST=$REDIS_HOST
            # - REDIS_PORT=$REDIS_PORT
        networks:
            - test_network

    
        

volumes:
    test-postgres-data:
    test-app-data:
    test-redis-data:

networks:
    test_network: