# In final implementation, move this file one diectory level higher and reference all services here
version: "3.9"

services:
    backend_api:
        build:
            context: 
                ./backendAPI
            target: dev
        image: backend_api:test
        environment:
            - ENVIRONMENT="test"
            - TEST_POSTGRES_DB=$POSTGRES_DB
            - TEST_POSTGRES_USER=$POSTGRES_USER
            - TEST_POSTGRES_PASSWORD=$POSTGRES_PASSWORD

    postgres:
        volumes:
            - test-postgres-data:/var/lib/postgresql/data/
        environment:
            - ENVIRONMENT="test"
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
    test-postgres-data: