version: "3.9"

services:
    backend_api:
        build:
            context: ./backendAPI
            target: prod
        # TBD: consider moving into compose.override.yml - in case a build stage is involved
        volumes:
            - ./backendAPI/src:/app
        ports:
            - "80:80"

    postgres:
        container_name: "postgres"
        image: postgres:16.1-alpine
