# version: "3.9"

services:
  backend_api:
    build:
      context: ./backendAPI
      target: prod
    volumes:
      - ./backendAPI:/app
    # ports:
    #     - "80:80"

  postgres:
    container_name: "postgres"
    image: postgres:16.1-alpine

  frontend_svelte:
    build:
      context: ./frontend_svelte

  redis:
    container_name: "redis"
    image: redis:8.2.2-alpine3.22
    command:
      - sh
      - -c
      - sh /data/entrypoint.sh
