version: "3.9"

services:
    backend_api:
        build:
            target: dev
        env_file:
            - ./backendAPI/src/.env
        ports:
            - "8660:8660"
        volumes:
            - dev-app-data:/data

    postgres:
        volumes:
            - dev-postgres-data:/var/lib/postgresql/data/
        env_file:
            - ./backendAPI/src/.env
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        env_file:
            - ./backendAPI/src/.env
        environment:
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
            - MASTER_PASSWORD_REQUIRED=False
        ports:
            - "5555:80"
        volumes:
            - dev-pgadmin-data:/var/lib/pgadmin
        restart: unless-stopped

volumes:
    dev-postgres-data:
    dev-pgadmin-data:
    dev-app-data: