# version: "3.9"

services:
  backend_api:
    build:
      context: ./backend
      target: api_prod
    volumes:
      - ./backend:/app
    # ports:
    #     - "80:80"

  backend_jobs:
    build:
      context: ./backend
      target: celery_prod
    volumes:
      - ./backend:/app

  postgres:
    container_name: "postgres"
    # Works in dev - wait until terraform azurerm supports version 18 for postgres, then update stage & prod!
    # image: postgres:18.0-alpine3.22
    image: postgres:16.1-alpine

  frontend_svelte:
    build:
      context: ./frontend_svelte

  redis:
    container_name: "redis"
    image: redis:8.2.2-alpine3.22
    command:
      - /bin/sh
      - /data/entrypoint.sh
