# version: "3.9"

services:
  backend_api:
    build:
      context: ./backendAPI
      target: prod
    volumes:
      - ./backendAPI:/app
    # ports:
    #     - "80:80"

  postgres:
    container_name: "postgres"
    image: postgres:16.1-alpine

  frontend_svelte:
    build:
      context: ./frontend_svelte

  redis:
    container_name: "redis"
    image: redis:8.2.2-alpine3.22
    volumes:
      - ./cacheRedis/redis.conf:/redis.conf:ro
      - ./cacheRedis/redis-full.conf:/redis-full.conf:ro
      # Note this would need to be rw if redis was to modify it via ACL commands and save the modifications.
      - ./cacheRedis/users_template.acl:/users_template.acl:ro
      - ./cacheRedis/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    command:
      - sh
      - -c
      - sh /usr/local/bin/entrypoint.sh
