version: "3.9"

services:
    backend_api:
        build:
            target: dev
        env_file:
            - ./backendAPI/src/.env
        ports:
            - "8660:80"
        volumes:
            - dev-app-data:/data
        networks:
            - dev_network

    postgres:
        container_name: dev_postgres
        # environment:
        #     - POSTGRES_HOST=$POSTGRES_HOST
        volumes:
            - dev-postgres-data:/var/lib/postgresql/data/
        env_file:
            - ./backendAPI/src/.env
        ports:
            - "5432:5432"
        networks:
            - dev_network

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        env_file:
            - ./backendAPI/src/.env
        environment:
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
            - MASTER_PASSWORD_REQUIRED=False
        ports:
            - "5555:80"
        volumes:
            - dev-pgadmin-data:/var/lib/pgadmin
        restart: unless-stopped
        networks:
            - dev_network

    # TBD: add .diockerignore to frontend_svelte
    frontend_svelte:
        build:
            target: build
        # env_file:
        #     - ./frontend_svelte/.env
        ports:
            - "8661:80"
        volumes:
            - ./frontend_svelte:/app
            - /app/node_modules
            # - ./frontend_svelte/node_modules:/app/node_modules
        networks:
            - dev_network
        command: 
            # sh -c "/bin/sh"
            npm run dev

volumes:
    dev-postgres-data:
    dev-pgadmin-data:
    dev-app-data:

networks:
    dev_network: