# fmt: off
# ruff: noqa
"""""

Revision ID: a0c481964dcf
Revises: 1bb7443317ce
Create Date: 2023-12-13 19:12:05.383754+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a0c481964dcf'
down_revision: Union[str, None] = '1bb7443317ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demoresource', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('demoresource', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demoresource', 'timezone')
    op.drop_column('demoresource', 'language')
    # ### end Alembic commands ###

# fmt: on
