# fmt: off
# ruff: noqa
"""""

Revision ID: ecfdc4d63db2
Revises: eee428d55a3b
Create Date: 2023-12-19 13:25:58.417714+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ecfdc4d63db2'
down_revision: Union[str, None] = 'eee428d55a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

# fmt: on
