# fmt: off
# ruff: noqa
"""""

Revision ID: 52a27a4fcaea
Revises: ecfdc4d63db2
Create Date: 2023-12-19 15:17:09.344545+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52a27a4fcaea'
down_revision: Union[str, None] = 'ecfdc4d63db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('demoresource', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'demoresource', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demoresource', type_='foreignkey')
    op.drop_column('demoresource', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###

# fmt: on
