"""test_migration

Revision ID: c03c94d7b339
Revises: 1bb7443317ce
Create Date: 2023-12-10 15:09:55.685795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c03c94d7b339"
down_revision: Union[str, None] = "1bb7443317ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "demoresource",
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("demoresource", "language")
    # ### end Alembic commands ###
