# fmt: off
# ruff: noqa
"""""

Revision ID: f484d8efa331
Revises: 71d5a55230a4
Create Date: 2024-02-02 19:45:24.266383+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f484d8efa331'
down_revision: Union[str, None] = '71d5a55230a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azuregroup',
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('azure_group_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('azure_group_id')
    )
    op.create_index(op.f('ix_azuregroup_azure_group_id'), 'azuregroup', ['azure_group_id'], unique=False)
    op.create_table('user',
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('azure_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_azure_user_id'), 'user', ['azure_user_id'], unique=False)
    op.create_table('azuregroupuserlink',
    sa.Column('azure_group_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('azure_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['azure_group_id'], ['azuregroup.azure_group_id'], ),
    sa.ForeignKeyConstraint(['azure_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('azure_group_id', 'azure_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azuregroupuserlink')
    op.drop_index(op.f('ix_user_azure_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_azuregroup_azure_group_id'), table_name='azuregroup')
    op.drop_table('azuregroup')
    # ### end Alembic commands ###

# fmt: on
