# fmt: off
# ruff: noqa
"""""

Revision ID: d3c5f159a166
Revises: 087ef64319d5
Create Date: 2024-02-27 10:46:58.198285+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3c5f159a166'
down_revision: Union[str, None] = '087ef64319d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protectedresource', sa.Column('last_accessed_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protectedresource', 'last_accessed_at')
    # ### end Alembic commands ###

# fmt: on
