# fmt: off
# ruff: noqa
# isort:skip_file
"""""

Revision ID: dfac770f790f
Revises: d3c5f159a166
Create Date: 2024-09-13 10:11:14.761612+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dfac770f790f'
down_revision: Union[str, None] = 'd3c5f159a166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identifiertypelink',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identifiertypelink_type'), 'identifiertypelink', ['type'], unique=False)
    op.create_table('identityhierarchy',
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('inherit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('parent_id', 'child_id'),
    sa.UniqueConstraint('parent_id', 'child_id')
    )
    op.create_table('resourcehierarchy',
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('inherit', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('parent_id', 'child_id'),
    sa.UniqueConstraint('parent_id', 'child_id')
    )
    op.create_table('accesslog',
    sa.Column('identity_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('action', sa.Enum('read', 'write', 'own', name='action'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identifiertypelink.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accesslog_action'), 'accesslog', ['action'], unique=False)
    op.create_index(op.f('ix_accesslog_identity_id'), 'accesslog', ['identity_id'], unique=False)
    op.create_index(op.f('ix_accesslog_resource_id'), 'accesslog', ['resource_id'], unique=False)
    op.create_index(op.f('ix_accesslog_time'), 'accesslog', ['time'], unique=False)
    op.create_table('accesspolicy',
    sa.Column('identity_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('action', sa.Enum('read', 'write', 'own', name='action'), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identifiertypelink.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'resource_id', 'action')
    )
    op.create_index(op.f('ix_accesspolicy_identity_id'), 'accesspolicy', ['identity_id'], unique=False)
    op.create_index(op.f('ix_accesspolicy_resource_id'), 'accesspolicy', ['resource_id'], unique=False)
    op.create_table('azuregroup',
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_azuregroup_id'), 'azuregroup', ['id'], unique=False)
    op.create_table('category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_table('protectedchild',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protectedgrandchild',
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protectedresource',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicresource',
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subgroup',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgroup_name'), 'subgroup', ['name'], unique=False)
    op.create_table('subsubgroup',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsubgroup_name'), 'subsubgroup', ['name'], unique=False)
    op.create_table('tag',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uebergroup',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uebergroup_name'), 'uebergroup', ['name'], unique=False)
    op.create_table('user',
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('azure_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_azure_user_id'), 'user', ['azure_user_id'], unique=True)
    op.create_table('azuregroupuserlink',
    sa.Column('azure_group_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('uuid_data', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['azure_group_id'], ['azuregroup.id'], ),
    sa.ForeignKeyConstraint(['uuid_data'], ['user.azure_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('azure_group_id', 'uuid_data')
    )
    op.create_table('demoresource',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demoresourcetaglink',
    sa.Column('demo_resource_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['demo_resource_id'], ['demoresource.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('demo_resource_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demoresourcetaglink')
    op.drop_table('demoresource')
    op.drop_table('azuregroupuserlink')
    op.drop_index(op.f('ix_user_azure_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_uebergroup_name'), table_name='uebergroup')
    op.drop_table('uebergroup')
    op.drop_table('tag')
    op.drop_index(op.f('ix_subsubgroup_name'), table_name='subsubgroup')
    op.drop_table('subsubgroup')
    op.drop_index(op.f('ix_subgroup_name'), table_name='subgroup')
    op.drop_table('subgroup')
    op.drop_table('publicresource')
    op.drop_table('protectedresource')
    op.drop_table('protectedgrandchild')
    op.drop_table('protectedchild')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    op.drop_table('category')
    op.drop_index(op.f('ix_azuregroup_id'), table_name='azuregroup')
    op.drop_table('azuregroup')
    op.drop_index(op.f('ix_accesspolicy_resource_id'), table_name='accesspolicy')
    op.drop_index(op.f('ix_accesspolicy_identity_id'), table_name='accesspolicy')
    op.drop_table('accesspolicy')
    op.drop_index(op.f('ix_accesslog_time'), table_name='accesslog')
    op.drop_index(op.f('ix_accesslog_resource_id'), table_name='accesslog')
    op.drop_index(op.f('ix_accesslog_identity_id'), table_name='accesslog')
    op.drop_index(op.f('ix_accesslog_action'), table_name='accesslog')
    op.drop_table('accesslog')
    op.drop_table('resourcehierarchy')
    op.drop_table('identityhierarchy')
    op.drop_index(op.f('ix_identifiertypelink_type'), table_name='identifiertypelink')
    op.drop_table('identifiertypelink')
    # ### end Alembic commands ###

# fmt: on
