# fmt: off
# ruff: noqa
"""""

Revision ID: bc60cd578fce
Revises: f484d8efa331
Create Date: 2024-02-02 19:51:18.116161+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc60cd578fce'
down_revision: Union[str, None] = 'f484d8efa331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

# fmt: on
