# fmt: off
# ruff: noqa
# isort:skip_file
"""""

Revision ID: 264046d1d607
Revises: 255fdcec93d4
Create Date: 2024-11-13 19:15:57.178138+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '264046d1d607'
down_revision: Union[str, None] = '255fdcec93d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'identityhierarchy', ['parent_id', 'child_id'])
    op.create_unique_constraint(None, 'resourcehierarchy', ['parent_id', 'child_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resourcehierarchy', type_='unique')
    op.drop_constraint(None, 'identityhierarchy', type_='unique')
    # ### end Alembic commands ###

# fmt: on
