# fmt: off
# ruff: noqa
# isort:skip_file
"""""

Revision ID: d1a083b31de9
Revises: bf35f2cf64ce
Create Date: 2025-01-08 11:23:38.822215+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1a083b31de9'
down_revision: Union[str, None] = 'bf35f2cf64ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resourcehierarchy_parent_id_order_key', 'resourcehierarchy', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('resourcehierarchy_parent_id_order_key', 'resourcehierarchy', ['parent_id', 'order'])
    # ### end Alembic commands ###

# fmt: on
