# fmt: off
# ruff: noqa
# isort:skip_file
"""""

Revision ID: b89043ed836e
Revises: ba36643125a7
Create Date: 2025-07-09 11:29:19.830835+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b89043ed836e'
down_revision: Union[str, None] = 'ba36643125a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azuregroupuserlink')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azuregroupuserlink',
    sa.Column('azure_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid_data', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['azure_group_id'], ['azuregroup.id'], name=op.f('azuregroupuserlink_azure_group_id_fkey')),
    sa.ForeignKeyConstraint(['uuid_data'], ['user.azure_user_id'], name=op.f('azuregroupuserlink_uuid_data_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('azure_group_id', 'uuid_data', name=op.f('azuregroupuserlink_pkey'))
    )
    # ### end Alembic commands ###

# fmt: on
