# fmt: off
# ruff: noqa
# isort:skip_file
"""""

Revision ID: bf35f2cf64ce
Revises: 63f43f0918f2
Create Date: 2025-01-08 01:15:31.876881+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf35f2cf64ce'
down_revision: Union[str, None] = '63f43f0918f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resourcehierarchy', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resourcehierarchy_order'), 'resourcehierarchy', ['order'], unique=False)
    op.create_unique_constraint(None, 'resourcehierarchy', ['parent_id', 'order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resourcehierarchy', type_='unique')
    op.drop_index(op.f('ix_resourcehierarchy_order'), table_name='resourcehierarchy')
    op.drop_column('resourcehierarchy', 'order')
    # ### end Alembic commands ###

# fmt: on
