# fmt: off
# ruff: noqa
""""67960140a5ab1adbe1e95c671b27e82a139dcb35"

Revision ID: 353a2db0d628
Revises: 7fdd24591664
Create Date: 2023-12-19 11:58:44.897231+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '353a2db0d628'
down_revision: Union[str, None] = '7fdd24591664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demoresource', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('demoresource', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    op.drop_column('demoresource', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demoresource', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('demoresource', 'last_updated_at')
    op.drop_column('demoresource', 'created_at')
    # ### end Alembic commands ###

# fmt: on
