# fmt: off
# ruff: noqa
""""86de6986f7550e358f8e88d31378713e9a999ede"

Revision ID: 373a42ea0c6d
Revises: 353a2db0d628
Create Date: 2023-12-20 22:17:03.951677+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '373a42ea0c6d'
down_revision: Union[str, None] = '353a2db0d628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('demoresource', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'demoresource', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'demoresource', type_='foreignkey')
    op.drop_column('demoresource', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###

# fmt: on
