# fmt: off
# ruff: noqa
""""7d1b60b8715e8af341ba239269b74304cd912e72"

Revision ID: 7fdd24591664
Revises: 50318f1098de
Create Date: 2023-12-12 15:23:51.477957+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7fdd24591664'
down_revision: Union[str, None] = '50318f1098de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demoresource', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('demoresource', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demoresource', 'timezone')
    op.drop_column('demoresource', 'language')
    # ### end Alembic commands ###

# fmt: on
