# fmt: off
# ruff: noqa
""""f5257e7b265a378eb2f3093a66007258863d178b"

Revision ID: ec9be1e364ce
Revises: d5376f459984
Create Date: 2024-02-23 15:38:25.474995+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec9be1e364ce'
down_revision: Union[str, None] = 'd5376f459984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_accessed_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_accessed_at')
    # ### end Alembic commands ###

# fmt: on
