# fmt: off
# ruff: noqa
""""9acd77537ca3a1966aaa7e9f69c1431a162b0c41"

Revision ID: 0ce45f140b27
Revises: 0a6e143a80b5
Create Date: 2024-12-16 15:47:27.159660+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ce45f140b27'
down_revision: Union[str, None] = '0a6e143a80b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_publicAIuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_publicAIuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###

# fmt: on
