# fmt: off
# ruff: noqa
""""78dc3d0aa1d1233627d68c9d3d32c04751588937"

Revision ID: 9a9a9647a458
Revises: 7c458bce08ec
Create Date: 2024-02-27 11:36:43.546865+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a9a9647a458'
down_revision: Union[str, None] = '7c458bce08ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protectedresource',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('protected_resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('protected_resource_id')
    )
    op.alter_column('user', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_accessed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('protectedresource')
    # ### end Alembic commands ###

# fmt: on
