# fmt: off
# ruff: noqa
""""3be21a1e3b64f8e1c6e81a5f5faa9f88b53d602c"

Revision ID: 7c458bce08ec
Revises: d5376f459984
Create Date: 2024-02-24 13:26:24.655212+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c458bce08ec'
down_revision: Union[str, None] = 'd5376f459984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_accessed_at')
    # ### end Alembic commands ###

# fmt: on
