# fmt: off
# ruff: noqa
""""2de80f3f8660c8f9b9c81cbee1b7342377a7ec9a"

Revision ID: 92cb012e71b2
Revises: d314a876d676
Create Date: 2024-01-18 23:53:45.570695+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92cb012e71b2'
down_revision: Union[str, None] = 'd314a876d676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('azure_group_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('azure_group_id')
    )
    op.create_index(op.f('ix_group_azure_group_id'), 'group', ['azure_group_id'], unique=False)
    op.create_table('user',
    sa.Column('azure_tenant_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('azure_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('azure_user_id')
    )
    op.create_index(op.f('ix_user_azure_user_id'), 'user', ['azure_user_id'], unique=False)
    op.create_table('groupuserlink',
    sa.Column('azure_group_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('azure_user_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['azure_group_id'], ['group.azure_group_id'], ),
    sa.ForeignKeyConstraint(['azure_user_id'], ['user.azure_user_id'], ),
    sa.PrimaryKeyConstraint('azure_group_id', 'azure_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groupuserlink')
    op.drop_index(op.f('ix_user_azure_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_group_azure_group_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###

# fmt: on
