# fmt: off
# ruff: noqa
""""4a35b61ba87e370d8017b6c269e4e4bebf4e6579"

Revision ID: 0a6e143a80b5
Revises: a097a5ebb41d
Create Date: 2024-12-15 11:10:22.043479+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0a6e143a80b5'
down_revision: Union[str, None] = 'a097a5ebb41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'identityhierarchy', ['parent_id', 'child_id'])
    op.create_unique_constraint(None, 'resourcehierarchy', ['parent_id', 'child_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resourcehierarchy', type_='unique')
    op.drop_constraint(None, 'identityhierarchy', type_='unique')
    # ### end Alembic commands ###

# fmt: on
