# fmt: off
# ruff: noqa
""""2e02663290c00d7da5ff455009cd15a39d430106"

Revision ID: c2f6009b2bb6
Revises: ac50dcb27b5b
Create Date: 2024-11-14 22:03:00.833263+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2f6009b2bb6'
down_revision: Union[str, None] = 'ac50dcb27b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demofile',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demofile_name'), 'demofile', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demofile_name'), table_name='demofile')
    op.drop_table('demofile')
    # ### end Alembic commands ###

# fmt: on
