# fmt: off
# ruff: noqa
""""f8c2a3b5b3436936827b0b5da74048bdf9832b44"

Revision ID: ae31b903bc5e
Revises: 93860947ce4e
Create Date: 2025-07-15 00:25:15.707965+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae31b903bc5e'
down_revision: Union[str, None] = '93860947ce4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azuregroupuserlink')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('azuregroupuserlink',
    sa.Column('azure_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('uuid_data', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['azure_group_id'], ['azuregroup.id'], name=op.f('azuregroupuserlink_azure_group_id_fkey')),
    sa.ForeignKeyConstraint(['uuid_data'], ['user.azure_user_id'], name=op.f('azuregroupuserlink_uuid_data_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('azure_group_id', 'uuid_data', name=op.f('azuregroupuserlink_pkey'))
    )
    # ### end Alembic commands ###

# fmt: on
