# fmt: off
# ruff: noqa
""""86db64365a3aa0770727048206c6b685307a1fa8"

Revision ID: 5c802fa452d2
Revises: 0ce45f140b27
Create Date: 2025-01-08 23:32:00.349624+01:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5c802fa452d2'
down_revision: Union[str, None] = '0ce45f140b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resourcehierarchy', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resourcehierarchy_order'), 'resourcehierarchy', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resourcehierarchy_order'), table_name='resourcehierarchy')
    op.drop_column('resourcehierarchy', 'order')
    # ### end Alembic commands ###

# fmt: on
