<h3 class="text-title md:text-title-large mt-4 text-info">Info Title</h3>
<p class="text-body-small md:text-body text-info">Info text-body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="text-title md:text-title-large mt-4 text-success">Success Title</h3>
<p class="text-body-small md:text-body text-success">Success text-body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="text-title md:text-title-large mt-4 text-warning">Warning Title</h3>
<p class="text-body-small md:text-body text-warning">Warning text-body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="text-title md:text-title-large mt-4 text-error">Error Title</h3>
<p class="text-body-small md:text-body text-error">Error text-body text</p>
<div class="divider divider-outline-variant"></div>
<p class="text-body-small text-outline-variant">The dividers are outline-variant</p>