<h3 class="text-title md:text-title-large mt-4 text-primary">Primary Title</h3>
<p class="text-body-small md:text-body text-primary">Primary text-body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="text-title md:text-title-large mt-4 text-secondary">Secondary Title</h3>
<p class="text-body-small md:text-body text-secondary">Secondary text-body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="text-title md:text-title-large mt-4 text-accent">Accent Title</h3>
<p class="text-body-small md:text-body text-accent">Accent text-body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="text-title md:text-title-large mt-4 text-neutral">Neutral Title</h3>
<p class="text-body-small md:text-body text-neutral">Neutral text-body text</p>
<div class="divider divider-outline-variant"></div>
<p class="text-body-small text-outline-variant">The dividers are outline-variant</p>