<h3 class="title md:title-large mt-4 text-primary">Primary Title</h3>
<p class="body-small md:body text-primary">Primary body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="title md:title-large mt-4 text-secondary">Secondary Title</h3>
<p class="body-small md:body text-secondary">Secondary body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="title md:title-large mt-4 text-accent">Accent Title</h3>
<p class="body-small md:body text-accent">Accent body text</p>
<div class="divider divider-outline-variant"></div>
<h3 class="title md:title-large mt-4 text-neutral">Neutral Title</h3>
<p class="body-small md:body text-neutral">Neutral body text</p>
<div class="divider divider-outline-variant"></div>
<p class="body-small text-outline-variant">The dividers are outline-variant</p>