services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
        UV_VERSION: ${UV_VERSION}
        BUN_VERSION: ${BUN_VERSION}
    command: sleep infinity
    init: true
    volumes:
      - .:/workspaces/fullStackSandbox23:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.ssh:/root/.ssh:ro