# fmt: off
# ruff: noqa
# isort:skip_file
"""""

Revision ID: 81db6c5b91e9
Revises: ae31b903bc5e
Create Date: 2025-10-03 18:26:29.029263+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81db6c5b91e9'
down_revision: Union[str, None] = 'ae31b903bc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column('ai_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('useraccount', 'is_publicAIuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useraccount', sa.Column('is_publicAIuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('useraccount', 'ai_enabled')
    # ### end Alembic commands ###

# fmt: on
