# fmt: off
# ruff: noqa
""""5b8c879b49104fa7eba6dc27614146e8e896ed7d"

Revision ID: 174fd5091128
Revises: 79fcc94dd0a4
Create Date: 2026-05-13 01:23:51.647027+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '174fd5091128'
down_revision: Union[str, None] = '79fcc94dd0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_presentation_path'), 'presentation', ['path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_presentation_path'), table_name='presentation')
    # ### end Alembic commands ###

# fmt: on
