# fmt: off
# ruff: noqa
""""05c44b77a2dc993867fadb0e4b70bfb87f5f6ab6"

Revision ID: 3798eb424fb9
Revises: c7f45d8b2a10
Create Date: 2026-09-26 14:51:30.684631+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3798eb424fb9'
down_revision: Union[str, None] = 'c7f45d8b2a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('linkedin_user_id', sa.String(collation='C'), nullable=True))
    op.create_index(op.f('ix_user_linkedin_user_id'), 'user', ['linkedin_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_linkedin_user_id'), table_name='user')
    op.drop_column('user', 'linkedin_user_id')
    # ### end Alembic commands ###

# fmt: on
