# fmt: off
# ruff: noqa
""""ff1a4396f962f5471a7505b74add8bd06016e311"

Revision ID: 3bd3ed7aa6d2
Revises: 174fd5091128
Create Date: 2026-08-18 19:52:03.046718+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bd3ed7aa6d2'
down_revision: Union[str, None] = '174fd5091128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_access_policy_public_resource', 'accesspolicy', ['resource_id'], unique=True, postgresql_where=sa.text('identity_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_access_policy_public_resource', table_name='accesspolicy', postgresql_where=sa.text('identity_id IS NULL'))
    # ### end Alembic commands ###

# fmt: on
