# fmt: off
# ruff: noqa
""""8ee0643bfba375216d21cef83d442c31ae91b571"

Revision ID: 649f0df56763
Revises: 3798eb424fb9
Create Date: 2026-09-29 14:51:23.474982+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '649f0df56763'
down_revision: Union[str, None] = '3798eb424fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('azuregroup', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('azuregroup', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

# fmt: on
