# fmt: off
# ruff: noqa
""""96162415031a36707cfb51945458f7b3b6acf5a9"

Revision ID: cd8c9c8baae7
Revises: 81db6c5b91e9
Create Date: 2026-01-16 14:57:03.479432+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd8c9c8baae7'
down_revision: Union[str, None] = '81db6c5b91e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demoresourcetaglink')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demoresourcetaglink',
    sa.Column('demo_resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['demo_resource_id'], ['demoresource.id'], name=op.f('demoresourcetaglink_demo_resource_id_fkey')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('demoresourcetaglink_tag_id_fkey')),
    sa.PrimaryKeyConstraint('demo_resource_id', 'tag_id', name=op.f('demoresourcetaglink_pkey'))
    )
    # ### end Alembic commands ###

# fmt: on
