# fmt: off
# ruff: noqa
""""c2279b95ca77c93b0cd0f1da196cde636c476900"

Revision ID: 0ab37093b18c
Revises: 906b2a043f40
Create Date: 2026-01-22 19:26:22.657651+01:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ab37093b18c'
down_revision: Union[str, None] = '906b2a043f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['identifiertypelink.id'], name=op.f('quiz_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_pkey'))
    )
    # ### end Alembic commands ###

# fmt: on
