# fmt: off
# ruff: noqa
""""8362477105842d664a4379ba612a9ac73bd698c3"

Revision ID: 1a668d9c2c31
Revises: 649f0df56763
Create Date: 2026-10-01 01:31:05.833421+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a668d9c2c31'
down_revision: Union[str, None] = '649f0df56763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('confidential', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'confidential')
    # ### end Alembic commands ###

# fmt: on
