<script lang="ts">
	import { Variant, Theming, type ColorConfig } from '$lib/theming';
	// // clean this mess up - mainly by moving to $lib/theming.ts
	// import {
	// 	argbFromHex,
	// 	hexFromArgb,
	// 	Hct,
	// 	// themeFromSourceColor,
	// 	// applyTheme,
	// 	// type Theme,
	// 	// lstarFromArgb,
	// 	// labFromArgb,
	// 	// xyzFromArgb,
	// 	TonalPalette,
	// 	customColor,
	// 	DynamicScheme,
	// 	SchemeContent,
	// 	SchemeExpressive,
	// 	SchemeFidelity,
	// 	SchemeFruitSalad,
	// 	SchemeMonochrome,
	// 	SchemeNeutral,
	// 	SchemeRainbow,
	// 	SchemeTonalSpot,
	// 	SchemeVibrant,

	// } from '@material/material-color-utilities';
	// import Color from 'colorjs.io'
	// import flyonUIThemes from 'flyonui/src/theming/themes';
	// const { light: lightFlyonUI, dark: darkFlyonUI } = flyonUIThemes;
	// import { light as lightFlyonUI, dark as darkFlyonUI } from 'flyonui/src/theming/themes';
	// import { Variant } from '@material/material-color-utilities/dynamiccolor/variant';
	import type { Action } from 'svelte/action';
	import NavButton from '$components/NavButton.svelte';
	import UserButton from '$components/UserButton.svelte';
	// import type { LayoutData } from '../$types';
	import { type Snippet } from 'svelte';
	import { page } from '$app/stores';
	import Guard from '$components/Guard.svelte';
	import ThemePicker from '$components/ThemePicker.svelte';
	// import JsonData from '$components/JsonData.svelte';
	// import { theme } from './layout.svelte';

	const theming = new Theming();

	let themeConfiguration: ColorConfig = $state({
		sourceColor: '#353c6e', // <= That's a good color!// '#769CDF',
		variant: Variant.TONAL_SPOT, // Variant.FIDELITY,//
		contrast: 0.0
	});
	// $effect(() => console.log('themeConfiguration:', themeConfiguration));

	// works:
	// let tenFold = $derived(theming.manipulateContrast(themeConfiguration.contrast))
	// $effect(() => console.log('tenFold:', tenFold));

	// clean this mess up - mainly by moving to $lib/theming.ts:
	// copy & paste from: https://github.com/material-foundation/material-color-utilities/blob/9889de141b3b5194b8574f9e378e55f4428bdb5e/typescript/dynamiccolor/variant.ts#L23C8-L33C2
	// as the export is missing in the package '@material/material-color-utilities'
	// switch to import { Variant } from '@material/material-color-utilities/dynamiccolor/variant';
	// from material-color-utilities version 0.3.1 onwards!
	// enum Variant {
	// 	MONOCHROME,
	// 	NEUTRAL,
	// 	TONAL_SPOT,
	// 	VIBRANT,
	// 	EXPRESSIVE,
	// 	FIDELITY,
	// 	CONTENT,
	// 	RAINBOW,
	// 	FRUIT_SALAD,
	// 	}

	// function (Variant: any) {
	// Variant[Variant["MONOCHROME"] = 0] = "MONOCHROME";
	// Variant[Variant["NEUTRAL"] = 1] = "NEUTRAL";
	// Variant[Variant["TONAL_SPOT"] = 2] = "TONAL_SPOT";
	// Variant[Variant["VIBRANT"] = 3] = "VIBRANT";
	// Variant[Variant["EXPRESSIVE"] = 4] = "EXPRESSIVE";
	// Variant[Variant["FIDELITY"] = 5] = "FIDELITY";
	// Variant[Variant["CONTENT"] = 6] = "CONTENT";
	// Variant[Variant["RAINBOW"] = 7] = "RAINBOW";
	// Variant[Variant["FRUIT_SALAD"] = 8] = "FRUIT_SALAD";
	// }
	// console.log(Variant)

	// import theme from './material-theme.json'

	// let { data, children }: { data: LayoutData; children: Snippet } = $props();
	let { children }: { children: Snippet } = $props();

	// TBD: ready to be used - check why the automatic creation makes a different scheme than
	// the one in from https://material-foundation.github.io/material-theme-builder/
	// Developer guide: https://github.com/material-foundation/material-color-utilities/tree/main/dev_guide
	// TBD: Add contrast this way: https://github.com/material-foundation/material-color-utilities/blob/main/dev_guide/refining_contrast.md
	let mainContent: HTMLDivElement;
	// // Get the theme from a hex color
	// const sourceColor = '#769CDF';
	// const sourceColorArgb = argbFromHex(sourceColor);
	// const sourceColorHct = Hct.fromInt(sourceColorArgb);
	// // const sourceColorHct = Hct.fromInt(sourceColorArgb);

	// // console.log('=== src - routes - (layout) - layout.svelte - sourceColor Hex / Argb ===');
	// // console.log(sourceColor, ' / ', sourceColorArgb);

	// // const theme = themeFromSourceColor(sourceColorArgb, [
	// 	// {
	// 	// 	name: "custom-1",
	// 	// 	value: argbFromHex("#ff0000"),
	// 	// 	blend: true,
	// 	// },
	// // ]);

	// // Print out the theme as JSON
	// // console.log('=== src - routes - (layout) - layout.svelte - themes ===');
	// // console.log(JSON.stringify(theme, null, 2));
	// // console.log('=== src - routes - (layout) - layout.svelte - hexFromArgb ===');

	// // From autogenerated color utilities:
	// // const primaryColor = hexFromArgb(theme['schemes']['light']['primary']);
	// // const sourceColor = hexFromArgb(theme['source']);
	// // From manually export from material theme builder:
	// // const primaryColor = theme['schemes']['light']['primary'];
	// // const seedColor = theme['seed'];

	// // console.log('primary: ', primaryColor);

	// // console.log("source: ", sourceColor);
	// // console.log("seedColor: ", seedColor);
	// // console.log(theme);

	// // create a dynamic scheme:
	// // from defintion:
	// // const dynamicScheme = new DynamicScheme(
	// // sourceColorHct: Hct;
	// // variant: Variant;
	// // contrastLevel: number;
	// // isDark: boolean;
	// // primaryPalette: TonalPalette;
	// // secondaryPalette: TonalPalette;
	// // tertiaryPalette: TonalPalette;
	// // neutralPalette: TonalPalette;
	// // neutralVariantPalette: TonalPalette;
	// // errorPalette?: TonalPalette;
	// // );
	// let contrast = $state(0.0);
	// // const dynamicSchemeLightNormalContrast = new DynamicScheme(
	// // 	{
	// // 		sourceColorArgb: sourceColorArgb,
	// // 		// MONOCHROME,
	// // 		// NEUTRAL,
	// // 		// TONAL_SPOT,
	// // 		// VIBRANT,
	// // 		// EXPRESSIVE,
	// // 		// FIDELITY,
	// // 		// CONTENT,
	// // 		// RAINBOW,
	// // 		// FRUIT_SALAD,
	// // 		variant: Variant.NEUTRAL,
	// // 		// 0.0 for default contrast.
	// // 		// 0.5 for higher contrast.
	// // 		// 1.0 for highest contrast.
	// // 		// -1.0 for reduced contrast.
	// // 		contrastLevel: 0.0,
	// // 		isDark: false,
	// // 		primaryPalette: theme['palettes']['primary'],
	// // 		secondaryPalette: theme['palettes']['secondary'],
	// // 		tertiaryPalette: theme['palettes']['tertiary'],
	// // 		neutralPalette: theme['palettes']['neutral'],
	// // 		neutralVariantPalette: theme['palettes']['neutralVariant'],
	// // 		// errorPalette: theme['palettes']['error'],
	// // 	}
	// // );
	// const dynamicSchemeLightNormalContrast = $derived(new SchemeTonalSpot(sourceColorHct, false, contrast))
	// // const dynamicSchemeDarkNormalContrast = new DynamicScheme(
	// // 	{
	// // 		sourceColorArgb: sourceColorArgb,
	// // 		variant: Variant.NEUTRAL,
	// // 		contrastLevel: 1,
	// // 		isDark: true,
	// // 		primaryPalette: theme['palettes']['primary'],
	// // 		secondaryPalette: theme['palettes']['secondary'],
	// // 		tertiaryPalette: theme['palettes']['tertiary'],
	// // 		neutralPalette: theme['palettes']['neutral'],
	// // 		neutralVariantPalette: theme['palettes']['neutralVariant'],
	// // 		// errorPalette: theme['palettes']['error'],
	// // 	}
	// // );
	// const dynamicSchemeDarkNormalContrast = $derived(new SchemeTonalSpot(sourceColorHct, true, contrast))
	// // console.log('=== src - routes - (layout) - layout.svelte - dynamicSchemeLightNormalContrast ===');
	// // console.log(dynamicSchemeLightNormalContrast);
	// // console.log('=== src - routes - (layout) - layout.svelte - dynamicSchemeDarkNormalContrast ===');
	// // console.log(dynamicSchemeDarkNormalContrast);

	// console.log('=== src - routes - (layout) - layout.svelte - dynamicSchemeLightNormalContrast[primary] ===');
	// console.log(dynamicSchemeLightNormalContrast.primary);

	// console.log('=== src - routes - (layout) - layout.svelte - lightFlyonUI.success ===');
	// console.log(lightFlyonUI.success);

	// let successFlyonUI = $state(new Color("oklch", parseFloat(lightFlyonUI.success.split(" "))));

	// // TBD. consider deriving this info from the material design "neutral" or "neutral-variant" palette!
	// // theses colors are generated from the old static part of Material 3, but they give a good correlation with the source Color:
	// const neutralColorGroup = customColor(sourceColorArgb, {value: argbFromHex(lightFlyonUI.neutral), name: 'flyonui-neutral', blend: true});
	// const infoColorGroup = customColor(sourceColorArgb, {value: argbFromHex(lightFlyonUI.info), name: 'flyonui-info', blend: true});
	// const successColorGroup = customColor(sourceColorArgb, {value: argbFromHex(lightFlyonUI.success), name: 'flyonui-success', blend: true});
	// const warningColorGroup = customColor(sourceColorArgb, {value: argbFromHex(lightFlyonUI.warning), name: 'flyonui-warning', blend: true});
	// // now creating a palette out of those to use with dynamic colors:
	// // TBD: consider feeding in the color from FlyonUI directly here, without the customColor function!
	// // Then create the colorGroup from the palette's key color!
	// const neutralPaletteLight = TonalPalette.fromInt(neutralColorGroup.light.color);
	// const neutralPaletteDark = TonalPalette.fromInt(neutralColorGroup.dark.color);
	// const infoPaletteLight = TonalPalette.fromInt(infoColorGroup.light.color);
	// const infoPaletteDark = TonalPalette.fromInt(infoColorGroup.dark.color);
	// const successPaletteLight = TonalPalette.fromInt(successColorGroup.light.color);
	// const successPaletteDark = TonalPalette.fromInt(successColorGroup.dark.color);
	// const warningPaletteLight = TonalPalette.fromInt(warningColorGroup.light.color);
	// const warningPaletteDark = TonalPalette.fromInt(warningColorGroup.dark.color);
	// console.log('=== src - routes - (layout) - layout.svelte - successColorGroup ===');
	// console.log(successColorGroup);
	// console.log('=== src - routes - (layout) - layout.svelte - neutralPaletteLight ===');
	// console.log(neutralPaletteLight);

	// TBD. create a customized theme here, that includes both light and dark mode as well as the custom colors  for it.
	// use that theme to map the tokens to the DOM
	// include the styling and font options there as well!

	// TBD: remove:
	// let customColorSuccessGroup = $state(customColor(sourceColorArgb, {
	// 	value: lightFlyonUI.success,
	// 	name: 'custom-success',
	// 	blend: true,
	// }))

	// let themeNormalContrast = $state({
	// 	source: sourceColorArgb,
	// 	schemes: {
	// 		light: dynamicSchemeLightNormalContrast,
	// 		dark: dynamicSchemeDarkNormalContrast,
	// 	},
	// 	palettes: {
	// 		primary: dynamicSchemeLightNormalContrast.primaryPalette,
	// 		secondary: dynamicSchemeLightNormalContrast.secondaryPalette,
	// 		tertiary: dynamicSchemeLightNormalContrast.tertiaryPalette,
	// 		neutral: dynamicSchemeLightNormalContrast.neutralPalette,
	// 		neutralVariant: dynamicSchemeLightNormalContrast.neutralVariantPalette,
	// 		error: dynamicSchemeLightNormalContrast.errorPalette,
	// 	},
	// 	customColors: []
	// });

	// console.log('=== src - routes - (layout) - layout.svelte - themeNormalContrast ===');
	// console.log(themeNormalContrast);

	let systemDark = $state(false);

	/* prettier-ignore */
	// const materialDesignSystemTokenNames = [
	// 	"primary", "on-primary", "primary-container", "on-primary-container",
	// 	"secondary", "on-secondary", "secondary-container", "on-secondary-container",
	// 	"tertiary", "on-tertiary", "tertiary-container", "on-tertiary-container",
	// 	"error", "on-error", "error-container", "on-error-container",
	// 	"primary-fixed", "primary-fixed-dim", "on-primary-fixed", "on-primary-fixed-variant", // avoid using those
	// 	"secondary-fixed", "secondary-fixed-dim", "on-secondary-fixed", "on-secondary-fixed-variant", // avoid using those
	// 	"tertiary-fixed", "tertiary-fixed-dim", "on-tertiary-fixed", "on-tertiary-fixed-variant", // avoid using those
	// 	"surface-container-lowest", "surface-container-low", "surface-container", "surface-container-high", "surface-container-highest",
	// 	"surface-dim", "surface", "surface-bright", // avoid using those
	// 	"on-surface", "on-surface-variant",
	// 	"outline", "outline-variant",
	// 	"inverse-surface", "inverse-on-surface", "inverse-primary",
	// 	"scrim", "shadow",
	// 	"neutral-palette-key-color", "neutral-variant-palette-key-color", // might be useful for mapping with FlyonUI
	// 	"primary-palette-key-color", "secondary-palette-key-color", "tertiary-palette-key-color", "error-palette-key-color", // avoid using those
	// 	"background", "on-background", // seems to be legacy
	// ]
	// const customExtensionTokens = [
	// 	"info", "on-info", "info-container", "on-info-container", // added to match FlyonUI
	// 	"success", "on-success", "success-container", "on-success-container",// added to match FlyonUI
	// 	"warning", "on-warning", "warning-container", "on-warning-container", // added to match FlyonUI
	// ]

	// type MaterialDesignToken = {
	// 	[key: string]: number;
	// }

	// let materialDesignTokensLightNormalContrast: MaterialDesignToken = $state({})
	// let materialDesignTokensDarkNormalContrast: MaterialDesignToken = $state({})
	// for (const token of materialDesignSystemTokenNames) {
	// 	const tokenNameCamelCase = token.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
	// 	const colorLight = dynamicSchemeLightNormalContrast[tokenNameCamelCase as keyof SchemeContent] as number;
	// 	const colorDark = dynamicSchemeDarkNormalContrast[tokenNameCamelCase as keyof SchemeContent] as number;
	// 	// if (typeof colorLight === 'number') {
	// 	materialDesignTokensLightNormalContrast[token] = colorLight;
	// 	// }
	// 	// if (typeof colorDark === 'number') {
	// 	materialDesignTokensDarkNormalContrast[token] = colorDark;
	// 	// }
	// }
	// console.log('=== src - routes - (layout) - layout.svelte - materialDesignTokens ===');
	// console.log(materialDesignTokensLightNormalContrast);
	let mode: "light" | "dark" = $state('dark');

	// let theme = $state({})

	// $effect(() => {setContext('theme', theme)});

	const applyTheming: Action = (_node) => {
		// read system setting dark / light mode on client side only - not during serve side rendering.
		// const systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
		systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
		mode = systemDark ? 'dark' : 'light';
		// let scheme = $derived(theming.applyTheme(themeConfiguration, mode, mainContent))
		// Works reactive:
		// $effect(() => console.log('scheme:', scheme));
		// necessary to apply the theme to the mainContent div:
		// $effect(() => { scheme })
		$effect(() => {
			// theming.applyTheme(themeConfiguration, mode, mainContent);
			theming.applyTheme(themeConfiguration, mode, document.documentElement);
			const styleElement = document.createElement('style');
			styleElement.textContent = ".bg-primary-container { background-color: var(--md-sys-color-primary-container); } .text-primary-container { color: var(--md-sys-color-primary-container); }";
			document.head.appendChild(styleElement);
			// theme.set(theming.applyTheme(themeConfiguration, mode, mainContent));
			// $page.data.theme = theme;
			// setContext('theme', theme)
			// console.log('=== src - routes - (layout) - layout.svelte - theme ===');
			// console.log(theme);

		});

		// console.log('=== src -routes - (layout) - applyMaterialDesignTheme - systemDark ===');
		// console.log(systemDark);

		// const materialDesignTokens = systemDark ? materialDesignTokensDarkNormalContrast : materialDesignTokensLightNormalContrast;
		// mode = systemDark ? 'dark' : 'light';

		// for (const token in materialDesignTokens) {
		// console.log(token + ": " + hexFromArgb(materialDesignTokens[token]));
		// TBD: change to mainElement
		// document.documentElement.style.setProperty(`--md-sys-color-${token}`, hexFromArgb(materialDesignTokens[token]));
		// mainContent.style.setProperty(`--md-sys-color-${token}`, hexFromArgb(materialDesignTokens[token]));

		// }
		// console.log('=== src - routes - (layout) - layout.svelte - applyMaterialDesignTheme - hexFromArgb(materialDesignTokens["surface-container"]) ===');
		// console.log(hexFromArgb(materialDesignTokens['surface-container']));
		// document.documentElement.style.backgroundColor = hexFromArgb(materialDesignTokens['background']);
		// mainContent.style.backgroundColor = hexFromArgb(materialDesignTokens['background']);

		// applyTheme(themeNormalContrast, { target: mainContent, dark: systemDark });

		// Apply the theme to the body by updating custom properties for material tokens
		// applyTheme(theme, { target: mainContent, dark: systemDark });
		// applyTheme(theme, { target: mainContent, dark: systemDark, brightnessSuffix: true });
	};

	// $effect(() => {
	// 	// console.log('=== src - routes - (layout) - layout.svelte - var --p - priority ===');
	// 	// console.log(document.documentElement.style.getPropertyPriority('var(--p)'))
	// 	console.log('=== src - routes - (layout) - layout.svelte - var --p - value ===');
	// 	console.log(document.documentElement.style.getPropertyValue('oklch(var(--p))'))
	// 	console.log('=== src - routes - (layout) - layout.svelte - var --md-sys-color-primary ===');
	// 	console.log(mainContent.style.getPropertyValue('--md-sys-color-primary'))
	// 	const primaryInt = theme['schemes']['light']['primary']
	// 	console.log("=== src - routes - (layout) - layout.svelte - theme['schemes']['light']['primary'] ===");
	// 	console.log(primaryInt);
	// 	const primaryHct = Hct.fromInt(primaryInt);
	// 	console.log("=== src - routes - (layout) - layout.svelte - primary Hct ===");
	// 	console.log(primaryHct);
	// 	// const primaryLstar = lstarFromArgb(primaryInt);
	// 	// console.log("=== src - routes - (layout) - layout.svelte - primaryLstar ===");
	// 	// console.log(primaryLstar);
	// 	const primaryLab = labFromArgb(primaryInt);
	// 	console.log("=== src - routes - (layout) - layout.svelte - primaryLab ===");
	// 	console.log(primaryLab);
	// 	const primaryXyz = xyzFromArgb(primaryInt);
	// 	console.log("=== src - routes - (layout) - layout.svelte - primaryXyz ===");
	// 	console.log(primaryXyz);
	// 	const primaryRgb = hexFromArgb(primaryInt);
	// 	console.log("=== src - routes - (layout) - layout.svelte - primaryRgb ===");
	// 	console.log(primaryRgb);
	// 	// const primaryRGBalpha = {
	// 	// 	red: redFromArgb(primaryInt),
	// 	// 	green: greenFromArgb(primaryInt),
	// 	// 	blue: blueFromArgb(primaryInt),
	// 	// 	alpha: alphaFromArgb(primaryInt),
	// 	// };
	// 	// console.log("=== src - routes - (layout) - layout.svelte - primaryRGBalpha ===");
	// 	// console.log(primaryRGBalpha);

	// 	// get the element with the data-theme attribute:
	// 	const dataThemeElement = document.querySelector('[data-theme]');
	// 	console.log('=== src - routes - (layout) - layout.svelte - dataThemeElement ===');
	// 	console.log(dataThemeElement);
	// 	console.log('=== src - routes - (layout) - layout.svelte - mainContent ===');
	// 	console.log(mainContent);

	// 	const originalValue = mainContent.style.getPropertyValue('--p');
	// 	console.log('=== src - routes - (layout) - layout.svelte - originalValue ===');
	// 	console.log(originalValue);
	// });

	// const overrideFlyonUIColors: Action = (_node) => {
	// 	// console.log('=== src - routes - (layout) - layout.svelte - overrideFlyonUIColors ===');
	// 	// document.documentElement.style.setProperty('--p', '(0.5 0.1 100)');
	// }

	// $effect(() => {
	// 	overrideFlyonUIColors(document.documentElement);
	// });

	// let mode = $state('light-high-contrast');
	// let mode = $state('light-hc');

	// static colors from Material 3:
	// const materialDesignPrimaryArgb = $state(theme['schemes']['light']['primary'])
	// const materialDesignPrimaryHct = $derived(Hct.fromInt(materialDesignPrimaryArgb))
	// const colorjsPrimary = $derived(new Color("hct", [materialDesignPrimaryHct.internalHue, materialDesignPrimaryHct.internalChroma, materialDesignPrimaryHct.internalTone]))

	// // use MaterialDynamicColors to get colors from DynamicScheme to apply to FlyonUI:
	// const materialDesignPrimaryArgb = $derived(dynamicSchemeLightNormalContrast["primary" as keyof SchemeContent] as number);
	// // or maybe hexFromArgb and feed hex to new Color()? - saves a conversion step.
	// const materialDesignPrimaryHct = $derived(Hct.fromInt(materialDesignPrimaryArgb));
	// // const colorjsPrimary = $derived(new Color("hct", [materialDesignPrimaryHct.internalHue, materialDesignPrimaryHct.internalChroma, materialDesignPrimaryHct.internalTone]))
	// const colorjsPrimary = $derived(new Color("hct", [materialDesignPrimaryHct.hue, materialDesignPrimaryHct.chroma, materialDesignPrimaryHct.tone]))
	// const primaryFromMaterialDesign = $derived(colorjsPrimary.to("oklch").coords.join(" "))
	// const primaryRGBalpha = {
	// 		red: redFromArgb(materialDesignPrimary),
	// 		green: greenFromArgb(materialDesignPrimary),
	// 		blue: blueFromArgb(materialDesignPrimary),
	// 		alpha: alphaFromArgb(materialDesignPrimary),
	// 	};
	// $effect(() => {
	// 	console.log("=== src - routes - (layout) - layout.svelte - materialDesignPrimaryHct ===");
	// 	console.log(materialDesignPrimaryHct);
	// 	console.log("=== src - routes - (layout) - layout.svelte - colorjsPrimary.to(oklch) ===");
	// 	console.log(colorjsPrimary.to("oklch"));
	// 	console.log(colorjsPrimary.to("oklch").coords);
	// 	console.log('=== src - routes - (layout) - layout.svelte - primaryFromMaterialDesign ===');
	// 	console.log(primaryFromMaterialDesign);

	// 	console.log(" ")

	// 	const primaryRGBalpha = {
	// 		red: redFromArgb(materialDesignPrimaryArgb),
	// 		green: greenFromArgb(materialDesignPrimaryArgb),
	// 		blue: blueFromArgb(materialDesignPrimaryArgb),
	// 		alpha: alphaFromArgb(materialDesignPrimaryArgb),
	// 	};
	// 	console.log("=== src - routes - (layout) - layout.svelte - primaryRGBalpha - from MaterialColor Utilities ===");
	// 	console.log(primaryRGBalpha);
	// 	console.log("=== src - routes - (layout) - layout.svelte - primaryRGBalpha - from Colorjs ===");
	// 	console.log(colorjsPrimary.to("srgb").coords[0] * 255, colorjsPrimary.to("srgb").coords[1] * 255, colorjsPrimary.to("srgb").coords[2] * 255);

	// });

	// let primaryManual = $state("77.5934% 0.247012 287.240256;")

	const toggleMode = () => {
		// mode = mode === 'dark-high-contrast' ? 'light-high-contrast' : 'dark-high-contrast';
		// mode = mode === 'dark-hc' ? 'light-hc' : 'dark-hc';
		mode = mode === 'dark' ? 'light' : 'dark';

		// const materialDesignTokens = mode === "dark" ? materialDesignTokensDarkNormalContrast : materialDesignTokensLightNormalContrast;

		// for (const token in materialDesignTokens) {
		// 	// console.log(token + ": " + hexFromArgb(materialDesignTokens[token]));
		// 	document.documentElement.style.setProperty(`--md-sys-color-${token}`, hexFromArgb(materialDesignTokens[token]));
		// }
		// TBD: This one applies the material design theme on a div inside main!
		// applyTheme(theme, { target: mainContent, dark: mode === 'dark' });
		// applyTheme(themeNormalContrast, { target: mainContent, dark: mode === 'dark' });
		// console.log('mode toggled to ' + mode);
		// document.documentElement.style.setProperty('--p', '(0.5 0.1 100)');
		// console.log('=== src - routes - (layout) - layout.svelte - changed --p ===');
		// console.log('=== src - routes - (layout) - layout.svelte - toggle - var --md-sys-color-primary ===');
		// const mdSysColorPrimary = mainContent.style.getPropertyValue('--md-sys-color-primary')
		// console.log(mdSysColorPrimary);

		// console.log('=== src - routes - (layout) - layout.svelte - document ===');
		// console.log(document)
		// primaryManual = mode === 'dark' ? "77.5934% 0.247012 287.240256;" : "37.5934% 0.247012 287.240256;";
		// primaryManual = mode === 'dark' ? "oklch(from #aac7ff l c h);" : "oklch(from #2a5ea7 l c h);";

		// console.log('=== src - routes - (layout) - layout.svelte - applyMaterialDesignTheme - hexFromArgb(materialDesignTokens["surface-container"]) ===');
		// console.log(hexFromArgb(materialDesignTokens['surface-container']));
		// TBD: should be implemented through the mode variable!
		// mainContent.style.backgroundColor = hexFromArgb(materialDesignTokens['background']);
		// document.documentElement.style.backgroundColor = hexFromArgb(materialDesignTokens['background']);
	};

	// const primaryManual = "(50% 0.2 0);"

	// const session = data?.sessionData;
	// const loggedIn = session?.loggedIn || false;
	const { loggedIn } = $page.data.session || false;
	// const { session } = $page.data;

	// let userPictureURL: URL | undefined = $state(undefined);
	// onMount(async () => {
	// 	// this call does not have any authentication - remove it!
	// 	const response = await fetch('/api/v1/user/me/picture', { method: 'GET' });
	// 	if (!response.ok && response.status !== 200) {
	// 		console.log('layout - userPictureURL - response not ok');
	// 		console.log(response);
	// 	} else {
	// 		const pictureBlob = await response.blob();
	// 		// console.log('layout - userPictureURL - pictureBlob');
	// 		// console.log(pictureBlob);
	// 		if (pictureBlob.size === 0) {
	// 			console.log('layout - userPictureURL - no User picture available');
	// 			console.log(pictureBlob);
	// 		} else {
	// 			userPictureURL = URL.createObjectURL(pictureBlob);
	// 			// console.log('layout - userPictureURL');
	// 			// console.log(userPictureURL);
	// 		}
	// 	}
	// });
</script>

<!-- style="--p: 0.45 .2 125" -->
<!-- TBD: this one applies the Material Design variables on the body! -->
<!-- <svelte:window use:applyMaterialDesignTheme use:overrideFlyonUIColors /> -->
<!-- <svelte:window use:applyMaterialDesignTheme /> -->

<!-- The class switches material design 3, whereas data-theme switches FlyonUI -->
<!-- <div bind:this={mainContent} class={`h-full ${mode}`} data-theme={mode} style="--p: {primaryManual};"> -->
<!-- <div bind:this={mainContent} class={`h-full ${mode}`} data-theme={mode} style="--p: {primaryFromMaterialDesign};" use:applyTheming> -->
<!-- <div bind:this={mainContent} class={`h-full ${mode}`} data-theme={mode} use:applyTheming> -->
<div bind:this={mainContent} class="h-full {mode}" data-theme={mode} use:applyTheming>
	<nav class="mx-2 p-2">
		<div class="flex w-full flex-wrap items-center justify-between">
			<div class="flex-grow space-x-4">
				<NavButton url="/" link="Home" />
				<NavButton url="/docs" link="Docs" />
				<NavButton url="/playground" link="Playground" />
				<Guard>
					<NavButton url="/protected" link="Protected" />
					<NavButton url="/dashboard" link="Dashboard" />
				</Guard>
			</div>
			<div class="flex space-x-4">
				<!-- Move this to component user button -->
				<!-- Implement check for user picture size and show svg instead, if no user picture available -->

				<!-- {#if loggedIn} -->
				<Guard>
					<img class="h-12 w-12 rounded-full" src="/api/v1/user/me/picture" alt="you" />
					{$page.data.session.microsoftProfile.displayName}
					<!-- TBD: remove the following one: -->
					<!-- {#if userPictureURL}
					<img class="h-12 w-12 rounded-full" src={userPictureURL} alt="you" />
				{/if} -->
				</Guard>
				<!-- {themeConfiguration.contrast} -->
				<ThemePicker bind:values={themeConfiguration} />
				<!-- {tenFold} -->
				<button aria-label="modeToggler">
					<label id="modeToggler" class="swap swap-rotate">
						<input type="checkbox" onclick={toggleMode} />
						<span class="icon-[tabler--sun] swap-on size-6"></span>
						<span class="icon-[tabler--moon] swap-off size-6"></span>
					</label>
				</button>
				<!-- {/if} -->
				<!-- Change this to using $page.data -> user -->
				{#if !loggedIn}
					<!-- <Guard> -->
					<!-- <NavButton url="/register" link="Register" invert /> -->
					<!-- data-sveltekit-preload-data="false" -->
					<!-- TBD: remove it here and set in hooks.Server.ts -->
					<NavButton pre_load={false} url={`/login?targetURL=${$page.url.href}`} link="Login" />
				{:else}
					<UserButton />
					<!-- needs to redirect to /home and delete session information -->
					<!-- TBD: write tests for logout -->
					<!-- data-sveltekit-preload-data="false" -->
					<NavButton pre_load={false} url="/logout" link="Logout" />
				{/if}
			</div>
		</div>
	</nav>

	<div>
		{@render children?.()}
	</div>

	<!-- <JsonData data={theme}></JsonData> -->
</div>

<style>
	/* :global {

		.bg-primary-container {
			background-color: var(--md-sys-color-primary-container);
		}
		.text-primary-container {
			color: var(--md-sys-color-primary-container);
		}
	} */
	/* @import './dark.css';
	@import './dark-hc.css';
	@import './dark-mc.css';
	@import './light.css';
	@import './light-hc.css';
	@import './light-mc.css'; */

	/* body {
		--p: rgb(65, 95, 145);
	} */
	/* :root {
    --my-color: #394DFF;
	} */
	/* background: #169C0F; */
	/* :root{
		--p: oklch(0.85 0.1 100);
	}

	:global(html, body) {
		
		--p: (0.7 0.1 100);
	}
	:global(.bg-primary) {
		background-color: var(--p);
	} */

	/* [data-theme=light] {
		color-scheme: light;
		--rounded-box: 0.5rem ;
		--rounded-btn: 0.375rem;
		--rounded-tooltip: 0.25rem;
		--animation-btn: 0.25s;
		--animation-input: .2s;
		--btn-focus-scale: 0.95;
		--border-btn: 1px;
		--tab-border: 1px;
		--tab-radius: 0.5rem;
		--p: 57.5934% 0.247012 287.240256;
		--pc: 93.7482% 0.032368 291.504163;
		--s: 55.7871% 0.022138 301.905408;
		--sc: 95.0453% 0.002858 308.427423;
		--a: 62.3083% 0.188015 259.814527;
		--ac: 93.1918% 0.031591 255.585479;
		--n: 40.6559% 0.025056 282.210785;
		--nc: 97.6419% 0.001323 286.375536;
		--b1: 100% 0 0;
		--b2: 94.7244% 0.005338 286.297402;
		--b3: 88.6277% 0.008239 278.622785;
		--bc: 37.567% 0.022158 281.800147;
		--bs: 37.567% 0.022158 281.800147;
		--in: 71.4837% 0.125737 215.220903;
		--inc: 95.6262% 0.044329 203.387778;
		--su: 73.1062% 0.216656 147.043973;
		--suc: 96.444% 0.02867 172.082912;
		--wa: 79.8713% 0.164239 73.09399;
		--wac: 98.4165% 0.02418 94.061776;
		--er: 65.3932% 0.222085 25.863858;
		--erc: 97.5752% 0.015143 61.349242;
		transparent: transparent;
		current: currentColor;
	}

	[data-theme=dark] {
		color-scheme: dark;
		--rounded-box: 0.5rem ;
		--rounded-btn: 0.375rem;
		--rounded-tooltip: 0.25rem;
		--animation-btn: 0.25s;
		--animation-input: .2s;
		--btn-focus-scale: 0.95;
		--border-btn: 1px;
		--tab-border: 1px;
		--tab-radius: 0.5rem;
		--p: 57.5934% 0.247012 287.240256;
		--pc: 93.7482% 0.032368 291.504163;
		--s: 55.7871% 0.022138 301.905408;
		--sc: 100% 0 0;
		--a: 62.3083% 0.188015 259.814527;
		--ac: 93.1918% 0.031591 255.585479;
		--n: 65.7482% 0.022235 294.952787;
		--nc: 18.5128% 0.016696 301.919165;
		--b1: 26.8442% 0.028285 299.769973;
		--b2: 22.6865% 0.023344 295.952775;
		--b3: 39.9632% 0.030791 300.243852;
		--bc: 78.094% 0.014175 295.24394;
		--bs: 18.5128% 0.016696 301.919165;
		--in: 71.4837% 0.125737 215.220903;
		--inc: 95.6262% 0.044329 203.387778;
		--su: 73.1062% 0.216656 147.043973;
		--suc: 96.444% 0.02867 172.082912;
		--wa: 79.8713% 0.164239 73.09399;
		--wac: 98.4165% 0.02418 94.061776;
		--er: 65.3932% 0.222085 25.863858;
		--erc: 97.5752% 0.015143 61.349242;
		transparent: transparent;
		current: currentColor;
	} */
</style>
