<script lang="ts">
	import {
		argbFromHex,
		hexFromArgb,
		Hct,
		themeFromSourceColor,
		applyTheme,
		lstarFromArgb,
		labFromArgb,
		xyzFromArgb,
		// DynamicScheme,
	} from '@material/material-color-utilities';
	// import { Variant } from '@material/material-color-utilities/dynamiccolor/variant';
	import type { Action } from 'svelte/action';
	import NavButton from '$components/NavButton.svelte';
	import UserButton from '$components/UserButton.svelte';
	// import type { LayoutData } from '../$types';
	import type { Snippet } from 'svelte';
	import { page } from '$app/stores';
	import Guard from '$components/Guard.svelte';

	// copy & paste from: https://github.com/material-foundation/material-color-utilities/blob/9889de141b3b5194b8574f9e378e55f4428bdb5e/typescript/dynamiccolor/variant.ts#L23C8-L33C2
	// as the export is missing in the package '@material/material-color-utilities'
	// enum Variant {
	// 	MONOCHROME,
	// 	NEUTRAL,
	// 	TONAL_SPOT,
	// 	VIBRANT,
	// 	EXPRESSIVE,
	// 	FIDELITY,
	// 	CONTENT,
	// 	RAINBOW,
	// 	FRUIT_SALAD
	// 	}

	// import theme from './material-theme.json'

	// let { data, children }: { data: LayoutData; children: Snippet } = $props();
	let { children }: { children: Snippet } = $props();

	// TBD: ready to be used - check why the automatic creation makes a different scheme than
	// the one in from https://material-foundation.github.io/material-theme-builder/
	// Developer guide: https://github.com/material-foundation/material-color-utilities/tree/main/dev_guide
	// TBD: Add contrast this way: https://github.com/material-foundation/material-color-utilities/blob/main/dev_guide/refining_contrast.md
	let mainContent: HTMLDivElement;
	// Get the theme from a hex color
	const sourceColor = '#769CDF';
	const sourceColorArgb = argbFromHex(sourceColor);
	// const sourceColorHct = Hct.fromInt(sourceColorArgb);

	// console.log('=== src - routes - (layout) - layout.svelte - sourceColor Hex / Argb ===');
	// console.log(sourceColor, ' / ', sourceColorArgb);

	const theme = themeFromSourceColor(sourceColorArgb, [
		// {
		// 	name: "custom-1",
		// 	value: argbFromHex("#ff0000"),
		// 	blend: true,
		// },
	]);

	// Print out the theme as JSON
	// console.log('=== src - routes - (layout) - layout.svelte - themes ===');
	// console.log(JSON.stringify(theme, null, 2));
	// console.log('=== src - routes - (layout) - layout.svelte - hexFromArgb ===');

	// From autogenerated color utilities:
	const primaryColor = hexFromArgb(theme['schemes']['light']['primary']);
	// const sourceColor = hexFromArgb(theme['source']);
	// From manually export from material theme builder:
	// const primaryColor = theme['schemes']['light']['primary'];
	// const seedColor = theme['seed'];

	// console.log('primary: ', primaryColor);

	// console.log("source: ", sourceColor);
	// console.log("seedColor: ", seedColor);
	// console.log(theme);

	// create a dynamic scheme:
	// from defintion:
	// const dynamicScheme = new DynamicScheme(
	// sourceColorHct: Hct;
	// variant: Variant;
	// contrastLevel: number;
	// isDark: boolean;
	// primaryPalette: TonalPalette;
	// secondaryPalette: TonalPalette;
	// tertiaryPalette: TonalPalette;
	// neutralPalette: TonalPalette;
	// neutralVariantPalette: TonalPalette;
	// errorPalette?: TonalPalette;
	// );
	// const dynamicScheme = new DynamicScheme(
	// 	{
	// 		sourceColorArgb: sourceColorArgb,
	// 		variant: Variant.NEUTRAL,
	// 		contrastLevel: 1,
	// 		isDark: false,
	// 		primaryPalette: theme['palettes']['primary'],
	// 		secondaryPalette: theme['palettes']['secondary'],
	// 		tertiaryPalette: theme['palettes']['tertiary'],
	// 		neutralPalette: theme['palettes']['neutral'],
	// 		neutralVariantPalette: theme['palettes']['neutralVariant'],
	// 		// errorPalette: theme['palettes']['error'],
	// 	}
	// );
	// console.log('=== src - routes - (layout) - layout.svelte - dynamicScheme ===');
	// console.log(dynamicScheme);

	const applyMaterialDesignTheme: Action = (_node) => {
		// read system setting dark / light mode on client side only - not during serve side rendering.
		const systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

		// console.log('=== src -routes - (layout) - applyMaterialDesignTheme - systemDark ===');
		// console.log(systemDark);

		// Apply the theme to the body by updating custom properties for material tokens
		applyTheme(theme, { target: mainContent, dark: systemDark });
		// applyTheme(theme, { target: mainContent, dark: systemDark, brightnessSuffix: true });
	};

	$effect(() => {
		// console.log('=== src - routes - (layout) - layout.svelte - var --p - priority ===');
		// console.log(document.documentElement.style.getPropertyPriority('var(--p)'))
		console.log('=== src - routes - (layout) - layout.svelte - var --p - value ===');
		console.log(document.documentElement.style.getPropertyValue('oklch(var(--p))'))
		console.log('=== src - routes - (layout) - layout.svelte - var --md-sys-color-primary ===');
		console.log(mainContent.style.getPropertyValue('--md-sys-color-primary'))
		const primaryInt = theme['schemes']['light']['primary']
		console.log("=== src - routes - (layout) - layout.svelte - theme['schemes']['light']['primary'] ===");
		console.log(primaryInt);
		const primaryHct = Hct.fromInt(primaryInt);
		console.log("=== src - routes - (layout) - layout.svelte - primary Hct ===");
		console.log(primaryHct);
		// const primaryLstar = lstarFromArgb(primaryInt);
		// console.log("=== src - routes - (layout) - layout.svelte - primaryLstar ===");
		// console.log(primaryLstar);
		const primaryLab = labFromArgb(primaryInt);
		console.log("=== src - routes - (layout) - layout.svelte - primaryLab ===");
		console.log(primaryLab);
		const primaryXyz = xyzFromArgb(primaryInt);
		console.log("=== src - routes - (layout) - layout.svelte - primaryXyz ===");
		console.log(primaryXyz);
		const primaryRgb = hexFromArgb(primaryInt);
		console.log("=== src - routes - (layout) - layout.svelte - primaryRgb ===");
		console.log(primaryRgb);
		console.log('=== src - routes - (layout) - layout.svelte - oklch(from rgb) ===');
	});
	


	const overrideFlyonUIColors: Action = (_node) => {
		// console.log('=== src - routes - (layout) - layout.svelte - overrideFlyonUIColors ===');
		// document.documentElement.style.setProperty('--p', '(0.5 0.1 100)');
		
	}
	
	// $effect(() => {
	// 	overrideFlyonUIColors(document.documentElement);
	// });

	// const session = data?.sessionData;
	// const loggedIn = session?.loggedIn || false;
	const { loggedIn } = $page.data.session || false;
	// const { session } = $page.data;

	// let mode = $state('light-high-contrast');
	// let mode = $state('light-hc');
	let mode = $state('light');

	const toggleMode = () => {
		// mode = mode === 'dark-high-contrast' ? 'light-high-contrast' : 'dark-high-contrast';
		// mode = mode === 'dark-hc' ? 'light-hc' : 'dark-hc';
		mode = mode === 'dark' ? 'light' : 'dark';
		// TBD: This one applies the material design theme on a div inside main!
		applyTheme(theme, { target: mainContent, dark: mode === 'dark' });
		console.log('mode toggled to ' + mode);
		// document.documentElement.style.setProperty('--p', '(0.5 0.1 100)');
		// console.log('=== src - routes - (layout) - layout.svelte - changed --p ===');
		console.log('=== src - routes - (layout) - layout.svelte - toggle - var --md-sys-color-primary ===');
		const mdSysColorPrimary = mainContent.style.getPropertyValue('--md-sys-color-primary')
		console.log(mdSysColorPrimary);
		// console.log('=== src - routes - (layout) - layout.svelte - document ===');
		// console.log(document)
	};

	// let userPictureURL: URL | undefined = $state(undefined);
	// onMount(async () => {
	// 	// this call does not have any authentication - remove it!
	// 	const response = await fetch('/api/v1/user/me/picture', { method: 'GET' });
	// 	if (!response.ok && response.status !== 200) {
	// 		console.log('layout - userPictureURL - response not ok');
	// 		console.log(response);
	// 	} else {
	// 		const pictureBlob = await response.blob();
	// 		// console.log('layout - userPictureURL - pictureBlob');
	// 		// console.log(pictureBlob);
	// 		if (pictureBlob.size === 0) {
	// 			console.log('layout - userPictureURL - no User picture available');
	// 			console.log(pictureBlob);
	// 		} else {
	// 			userPictureURL = URL.createObjectURL(pictureBlob);
	// 			// console.log('layout - userPictureURL');
	// 			// console.log(userPictureURL);
	// 		}
	// 	}
	// });
</script>

<!-- style="--p: 0.45 .2 125" -->
<!-- TBD: this one applies the Material Design variables on the body! -->
<svelte:window use:applyMaterialDesignTheme use:overrideFlyonUIColors />

<!-- The class switches material design 3, whereas data-theme switches FlyonUI -->
<div bind:this={mainContent} class={`h-full ${mode}`} data-theme={mode}>
	<nav class="mx-2 p-2">
		<div class="flex w-full flex-wrap items-center justify-between">
			<div class="flex-grow space-x-4">
				<NavButton url="/" link="Home" />
				<NavButton url="/docs" link="Docs" />
				<NavButton url="/playground" link="Playground" />
				<Guard>
					<NavButton url="/protected" link="Protected" />
					<NavButton url="/dashboard" link="Dashboard" />
				</Guard>
			</div>
			<div class="flex space-x-4">
				<!-- Move this to component user button -->
				<!-- Implement check for user picture size and show svg instead, if no user picture available -->

				<!-- {#if loggedIn} -->
				<Guard>
					<img class="h-12 w-12 rounded-full" src="/api/v1/user/me/picture" alt="you" />
					{$page.data.session.microsoftProfile.displayName}
					<!-- TBD: remove the following one: -->
					<!-- {#if userPictureURL}
					<img class="h-12 w-12 rounded-full" src={userPictureURL} alt="you" />
				{/if} -->
				</Guard>
				<button aria-label="modeToggler">
					<label id="modeToggler" class="swap swap-rotate">
						<input type="checkbox" onclick={toggleMode} />
						<span class="icon-[tabler--sun] swap-on size-6"></span>
						<span class="icon-[tabler--moon] swap-off size-6"></span>
					</label>
				</button>
				<!-- {/if} -->
				<!-- Change this to using $page.data -> user -->
				{#if !loggedIn}
					<!-- <Guard> -->
					<!-- <NavButton url="/register" link="Register" invert /> -->
					<!-- data-sveltekit-preload-data="false" -->
					<!-- TBD: remove it here and set in hooks.Server.ts -->
					<NavButton pre_load={false} url={`/login?targetURL=${$page.url.href}`} link="Login" />
				{:else}
					<UserButton />
					<!-- needs to redirect to /home and delete session information -->
					<!-- TBD: write tests for logout -->
					<!-- data-sveltekit-preload-data="false" -->
					<NavButton pre_load={false} url="/logout" link="Logout" />
				{/if}
			</div>
		</div>
	</nav>

	<!-- <JsonData data={$page}></JsonData> -->

	<div>
		{@render children?.()}
	</div>
</div>

<style>
	/* @import './dark.css';
	@import './dark-hc.css';
	@import './dark-mc.css';
	@import './light.css';
	@import './light-hc.css';
	@import './light-mc.css'; */

	/* body {
		--p: rgb(65, 95, 145);
	} */
	/* :root {
    --my-color: #394DFF;
	} */
	 /* background: #169C0F; */
	/* :root{
		--p: oklch(0.85 0.1 100);
	}

	:global(html, body) {
		
		--p: (0.7 0.1 100);
	}
	:global(.bg-primary) {
		background-color: var(--p);
	} */

	[data-theme=light] {
		color-scheme: light;
		--rounded-box: 0.5rem ;
		--rounded-btn: 0.375rem;
		--rounded-tooltip: 0.25rem;
		--animation-btn: 0.25s;
		--animation-input: .2s;
		--btn-focus-scale: 0.95;
		--border-btn: 1px;
		--tab-border: 1px;
		--tab-radius: 0.5rem;
		--p: 57.5934% 0.247012 287.240256;
		--pc: 93.7482% 0.032368 291.504163;
		--s: 55.7871% 0.022138 301.905408;
		--sc: 95.0453% 0.002858 308.427423;
		--a: 62.3083% 0.188015 259.814527;
		--ac: 93.1918% 0.031591 255.585479;
		--n: 40.6559% 0.025056 282.210785;
		--nc: 97.6419% 0.001323 286.375536;
		--b1: 100% 0 0;
		--b2: 94.7244% 0.005338 286.297402;
		--b3: 88.6277% 0.008239 278.622785;
		--bc: 37.567% 0.022158 281.800147;
		--bs: 37.567% 0.022158 281.800147;
		--in: 71.4837% 0.125737 215.220903;
		--inc: 95.6262% 0.044329 203.387778;
		--su: 73.1062% 0.216656 147.043973;
		--suc: 96.444% 0.02867 172.082912;
		--wa: 79.8713% 0.164239 73.09399;
		--wac: 98.4165% 0.02418 94.061776;
		--er: 65.3932% 0.222085 25.863858;
		--erc: 97.5752% 0.015143 61.349242;
		transparent: transparent;
		current: currentColor;
	}

	[data-theme=dark] {
		color-scheme: dark;
		--rounded-box: 0.5rem ;
		--rounded-btn: 0.375rem;
		--rounded-tooltip: 0.25rem;
		--animation-btn: 0.25s;
		--animation-input: .2s;
		--btn-focus-scale: 0.95;
		--border-btn: 1px;
		--tab-border: 1px;
		--tab-radius: 0.5rem;
		--p: 57.5934% 0.247012 287.240256;
		/* --p: oklch(from #2a5ea7 calc(l + 0.1) c h); */
		--pc: 93.7482% 0.032368 291.504163;
		--s: 55.7871% 0.022138 301.905408;
		--sc: 100% 0 0;
		--a: 62.3083% 0.188015 259.814527;
		--ac: 93.1918% 0.031591 255.585479;
		--n: 65.7482% 0.022235 294.952787;
		--nc: 18.5128% 0.016696 301.919165;
		--b1: 26.8442% 0.028285 299.769973;
		--b2: 22.6865% 0.023344 295.952775;
		--b3: 39.9632% 0.030791 300.243852;
		--bc: 78.094% 0.014175 295.24394;
		--bs: 18.5128% 0.016696 301.919165;
		--in: 71.4837% 0.125737 215.220903;
		--inc: 95.6262% 0.044329 203.387778;
		--su: 73.1062% 0.216656 147.043973;
		--suc: 96.444% 0.02867 172.082912;
		--wa: 79.8713% 0.164239 73.09399;
		--wac: 98.4165% 0.02418 94.061776;
		--er: 65.3932% 0.222085 25.863858;
		--erc: 97.5752% 0.015143 61.349242;
		transparent: transparent;
		current: currentColor;
	}
</style>
