name: "Deploying Stage"

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  REGISTRY: ghcr.io

jobs:
    backend:
        runs-on: ubuntu-22.04
        environment: stage
        steps:
            - uses: actions/checkout@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build for production
              run: |
                IMAGE_NAME=backend_api
                COMMIT_IMAGE=$IMAGE_NAME:$GITHUB_SHA
                LATEST_IMAGE=$IMAGE_NAME:latest
                docker compose -f compose.yml build
                docker image ps
            # TBD: add container registry:
                # docker tag $IMAGE_NAME $COMMIT_IMAGE
                # docker tag $IMAGE_NAME $LATEST_IMAGE
            - name: Push to github container registry
              run: |
                docker push $COMMIT_IMAGE
                docker push $LATEST_IMAGE
            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Azure CLI script
              uses: azure/CLI@v1
              with:
                azcliversion: latest
                inlineScript: |
                  az account show
            - name: Deploy to staging
              run: echo "Deploying to staging"
            #   TBD: move production deployment to a separate workflow - trigger: workflow_dispatch (which is manual