name: "Deploying Stage"

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    backend:
        runs-on: ubuntu-22.04
        environment: stage
        steps:
            - uses: actions/checkout@v3
            - name: Build for production
              run: docker compose -f compose.yml build
            # - name: Push to github container registry
            #   run: 
            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            - name: Azure CLI script
              uses: azure/CLI@v1
              with:
                azcliversion: latest
                inlineScript: |
                  az account show
            - name: Deploy to staging
              run: echo "Deploying to staging"
            #   TBD: move production deployment to a separate workflow - trigger: workflow_dispatch (which is manual