name: Deploying

on:
  workflow_run:
    workflows: ["Testing"]
    types:
      - completed
    branches:
      - main

jobs:
    backend:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Build for production
              run: echo "Building for production"
            - name: Build to staging
              run: echo "Deploying to staging"