name: "Deploying Production"

on:
  # workflow_dispatch: # allows to run the workflow manually
  # But: the manual review is now controlled through the environment, which requires a manual approval
  workflow_run:
    workflows: ["Deploying Stage"]
    types:
      - completed
    branches: [main]

env:
  REGISTRY: ghcr.io
  CONTAINER_REPO: $REGISTRY/${{ github.repository_owner }}

jobs:
  deploy_prod:
    if: ${{ github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      packages: read
    environment: prod
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to production
      # TBD: changing mode to single here, as there is a terraform bug with the time-out, when setting containerapp to single!
        run: |
          az containerapp revision set-mode --name ${{ vars.AZURE_CONTAINERAPP_BACKEND }} --resource-group ${{vars.AZURE_RESOURCE_GROUP}} --mode single
          az containerapp update --name ${{ vars.AZURE_CONTAINERAPP_BACKEND }} --resource-group ${{vars.AZURE_RESOURCE_GROUP}} --image ${{env.CONTAINER_REPO}}/${{github.repository}}-backend_api:$GITHUB_SHA
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear