name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  # pull_request:
  #   paths:
  #     - 'frontend/**'
      

jobs:
  dummy:
    runs-on: ubuntu-22.04
    environment: test
    steps:
    - name: Dummy
      run: echo "Dummy"
    # - uses: actions/checkout@v3
    # - name: Build
    #   run: |
          # docker compose \
          # -f compose.yml \
          # -f compose.override.test.yml \
          # build frontend
    # - name: Code Formating
    #   run: |
        # docker compose \
        # -f compose.yml \
        # -f compose.override.test.yml \
        # run --rm frontend \
        # sh -c "npm run format"