name: Infrastructure

on:
  push:
    branches:
      - dev
      - stage
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  plan_and_apply:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup OpenTofu
      #   uses: opentofu/setup-opentofu@v1
      #   with:
      #     tofu_version: 1.8.2

      # - name: OpenTofu Init
      #   run: tofu init

      # remember to tofu workspace select [dev, stage, prod] depending on the branch [dev, stage, main]
      # - name: OpenTofu Workspace
      #   run: tofu workspace select {{ some variable to select workspace }}

      # - name: OpenTofu Plan
      #   run: tofu plan

      # - name: OpenTofu Apply
      #   run: tofu apply -auto-approve

      # - name: OpenTofu Output
      #   run: tofu output

      # remmeber to write the relevant tofu files into the infrastructure folder via commit!

  # backend:
  #   needs: plan_and_apply
  #   uses: ./.github/workflows/backendAPI.yml
  #   secrets: inherit

  # frontend:
  #   needs: plan_and_apply
  #   uses: ./.github/workflows/frontend_svelte.yml
  #   secrets: inherit