name: Infrastructure

on:
  push:
    branches:
      - dev
      - stage
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  plan_and_apply:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.9.5

      # - name: Terraform Init
      #   run: terraform init

      # remember to terraform workspace select [dev, stage, prod] depending on the branch [dev, stage, main]
      # - name: Terraform Workspace
      #   run: terraform workspace select {{ some variable to select workspace }}

      # - name: Terraform Plan
      #   run: terraform plan


  # OK, let's see if this triggers the frontend workflow now.

  # backend:
  #   needs: plan_and_apply
  #   uses: ./.github/workflows/backendAPI.yml
  #   secrets: inherit

  # frontend:
  #   needs: plan_and_apply
  #   uses: ./.github/workflows/frontend_svelte.yml
  #   secrets: inherit