name: Infrastructure

on:
  push:
    branches:
      - dev
      - stage
      - main
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  plan_and_apply:
    runs-on: ubuntu-24.04

    steps:
      # Remove Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # one step here only - just for manual trigger of the protection rule. Once infrastructure is ready, the manual approval of protection rule will trigger the next steps including the backend and frontend deployment
      # nope - let's do that for real!!!

      - name: Build infrastructure image
        run: |
          cd infrastructure
          docker compose build
          cd scripts

      - name: Run tofu version
        run: |
          pwd
          ls -la
          cd infrastructure/scripts
          ./version.sh tofu version

      - name: Run tofu help
        run: |
          cd infrastructure/scripts
          ./help.sh

      - name: Formating infrastructure files with tofu fmt
        run: |
          cd infrastructure/scripts
          ./fmt.sh
      # if the formatting fails, the pipeline will fail and the developer will have to fix the formatting issues before the pipeline can pass
      

      # - name: Setup OpenTofu
      #   uses: opentofu/setup-opentofu@v1
      #   with:
      #     tofu_version: 1.8.2

      # - name: OpenTofu Init
      #   run: tofu init

      # remember to tofu workspace select [dev, stage, prod] depending on the branch [dev, stage, main]
      # - name: OpenTofu Workspace
      #   run: tofu workspace select {{ some variable to select workspace }}

      # - name: OpenTofu Plan
      #   run: tofu plan

      # - name: OpenTofu Apply
      #   run: tofu apply -auto-approve

      # - name: OpenTofu Output
      #   run: tofu output

      # remmeber to write the relevant tofu files into the infrastructure folder via commit!

  # backend:
  #   needs: plan_and_apply
  #   uses: ./.github/workflows/backendAPI.yml
  #   secrets: inherit

  # frontend:
  #   needs: plan_and_apply
  #   uses: ./.github/workflows/frontend_svelte.yml
  #   secrets: inherit