name: Infrastructure

on:
  push:
    paths:
      - 'infrastrucutre/**'
      - '.github/workflows/infrastructure.yml'

jobs:
  plan_and_apply:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.9.5

      # - name: Terraform Init
      #   run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

  run_backend:
    needs: plan_and_apply
    uses: ./.github/workflows/backendAPI.yml

  run_frontend:
    needs: plan_and_apply
    uses: ./.github/workflows/frontend_svelte.yml